[package]
name = "game-of-life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
itertools = "0.10"
rand = "0.8"
strum = { version = "0.24", features = ["derive"] }
