name: Deploy to GitHub pages

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: install system dependencies
#        run: apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
      - name: add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: build
        run: cargo build --target wasm32-unknown-unknown
